version: "3.8"

services:
  postgres:
    image: postgres:16-alpine
    container_name: postgres
    restart: unless-stopped
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgre123
      - POSTGRES_DB=event_booking
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - app-network

  backend:
    build: ./backend
    container_name: backend
    restart: unless-stopped
    depends_on:
      - postgres
    ports:
      - "5000:5000"
    env_file:
      - ./backend/.env
    networks:
      - app-network

  frontend:
    build: ./frontend
    container_name: frontend
    restart: unless-stopped
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  pgdata:
